// This file is automatically generated by tools/GenerateAst.kt. Do not edit directly.

package kotlox

abstract class Expr {
  interface Visitor<R> {
    fun visitAssignExpr(expr: Expr.Assign): R
    fun visitBinaryExpr(expr: Expr.Binary): R
    fun visitCallExpr(expr: Expr.Call): R
    fun visitGetExpr(expr: Expr.Get): R
    fun visitGroupingExpr(expr: Expr.Grouping): R
    fun visitLiteralExpr(expr: Expr.Literal): R
    fun visitLogicalExpr(expr: Expr.Logical): R
    fun visitSetExpr(expr: Expr.Set): R
    fun visitSuperExpr(expr: Expr.Super): R
    fun visitThisExpr(expr: Expr.This): R
    fun visitUnaryExpr(expr: Expr.Unary): R
    fun visitVariableExpr(expr: Expr.Variable): R
  }
class Assign(val name: Token, val value: Expr) : Expr() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitAssignExpr(this)
    }
}
class Binary(val left: Expr, val operator: Token, val right: Expr) : Expr() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitBinaryExpr(this)
    }
}
class Call(val callee: Expr, val paren: Token, val arguments: Iterable<Expr>) : Expr() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitCallExpr(this)
    }
}
class Get(val obj: Expr, val name: Token) : Expr() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitGetExpr(this)
    }
}
class Grouping(val expression: Expr) : Expr() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitGroupingExpr(this)
    }
}
class Literal(val value: Any?) : Expr() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitLiteralExpr(this)
    }
}
class Logical(val left: Expr, val operator: Token, val right: Expr) : Expr() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitLogicalExpr(this)
    }
}
class Set(val obj: Expr, val name: Token, val value: Expr) : Expr() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitSetExpr(this)
    }
}
class Super(val keyword: Token, val method: Token) : Expr() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitSuperExpr(this)
    }
}
class This(val keyword: Token) : Expr() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitThisExpr(this)
    }
}
class Unary(val operator: Token, val right: Expr) : Expr() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitUnaryExpr(this)
    }
}
class Variable(val name: Token) : Expr() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitVariableExpr(this)
    }
}

  abstract fun <R> accept(visitor: Visitor<R>): R
}
