// This file is automatically generated by tools/GenerateAst.kt. Do not edit directly.

package kotlox

abstract class Stmt {
  interface Visitor<R> {
    fun visitExpressionStmt(expr: Stmt.Expression): R
    fun visitPrintStmt(expr: Stmt.Print): R
    fun visitVarStmt(expr: Stmt.Var): R
    fun visitBlockStmt(expr: Stmt.Block): R
    fun visitIfStmt(expr: Stmt.If): R
    fun visitWhileStmt(expr: Stmt.While): R
  }
class Expression(val expression: Expr) : Stmt() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitExpressionStmt(this)
    }
}
class Print(val expression: Expr) : Stmt() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitPrintStmt(this)
    }
}
class Var(val name: Token, val initializer: Expr?) : Stmt() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitVarStmt(this)
    }
}
class Block(val statements: List<Stmt>) : Stmt() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitBlockStmt(this)
    }
}
class If(val condition: Expr, val thenBranch: Stmt, val elseBranch: Stmt?) : Stmt() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitIfStmt(this)
    }
}
class While(val condition: Expr, val body: Stmt) : Stmt() {
    override fun <R> accept(visitor: Visitor<R>): R {
        return visitor.visitWhileStmt(this)
    }
}

  abstract fun <R> accept(visitor: Visitor<R>): R
}
