package kotlox

enum class TokenType{

    //SINGLE CHARACTER TOKENS
    LPAREN, RPAREN, LBRACE, RBRACE, 
    COMMA, SEMICOLON, DOT, 
    PLUS, MINUS, STAR, SLASH,

    //ONE OR TWO CHARACTER TOKENS
    BANG, BANG_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,

    //LITERALS
    IDENTIFIER, STRING, NUMBER,

    //KEYWORDS
    AND, CLASS, ELSE, FALSE,
    FUN, FOR, IF, NIL,
    OR, PRINT, RETURN, SUPER, 
    THIS, TRUE, VAR, WHILE,

    EOF
}