package kotlox.tools

import java.io.IOException
import java.io.PrintWriter
import kotlin.system.exitProcess

class GenerateAst {
    companion object {
        @JvmStatic
        fun main(args: Array<String>) {
            if (args.size != 1) {
                System.err.println("Usage: generate_ast <output directory>")
                exitProcess(1)
            }
            val outputDir = args[0]

            // Expr.kt
            defineAst(
                outputDir, "Expr", listOf(
                    "Assign   : Token name, Expr value",
                    "Binary   : Expr left, Token operator, Expr right",
                    "Call     : Expr callee, Token paren, Iterable<Expr> arguments",
                    "Get      : Expr obj, Token name",
                    "Grouping : Expr expression",
                    "Literal  : Any? value",
                    "Logical  : Expr left, Token operator, Expr right",
                    "Set      : Expr obj, Token name, Expr value",
                    "Super    : Token keyword, Token method",
                    "This     : Token keyword",
                    "Unary    : Token operator, Expr right",
                    "Variable : Token name"
                )
            )

            // Stmt.kt
            defineAst(
                outputDir, "Stmt", listOf(
                    "Expression : Expr expression",
                    "Print      : Expr expression",
                    "Var        : Token name, Expr? initializer",
                    "Block      : List<Stmt> statements",
                    "If         : Expr condition, Stmt thenBranch, Stmt? elseBranch",
                    "While      : Expr condition, Stmt body"
                )
            )

        }

        @Throws(IOException::class)
        private fun defineAst(outputDir: String, baseName: String, typeList: List<String>) {
            val types = typeList.map {
                val (className, fieldsRaw) = it.split(":").map(String::trim)
                val fields = fieldsRaw.split(", ").map { field ->
                    val parts = field.split(" ")
                    parts[0] to parts[1]
                }
                className to fields
            }

            val path = "$outputDir/$baseName.kt"
            val writer = PrintWriter(path, "UTF-8")

            writer.println("// This file is automatically generated by tools/GenerateAst.kt. Do not edit directly.")
            writer.println()
            writer.println("package kotlox")
            writer.println()
            writer.println("abstract class $baseName {")

            // Visitor interface
            defineVisitor(writer, baseName, types.map { it.first })

            // AST classes
            for ((className, fields) in types) {
                defineType(writer, baseName, className, fields)
            }

            writer.println()
            writer.println("  abstract fun <R> accept(visitor: Visitor<R>): R")
            writer.println("}")
            writer.close()
        }

        private fun defineVisitor(writer: PrintWriter, baseName: String, types: List<String>) {
            writer.println("  interface Visitor<R> {")
            for (type in types) {
                writer.println("    fun visit${type}${baseName}(expr: $baseName.$type): R")
            }
            writer.println("  }")
        }


        private fun defineType(
            writer: PrintWriter, baseName: String,
            className: String, fieldList: List<Pair<String, String>>
        ) {
            val fields = fieldList.joinToString(", ") { "val ${it.second}: ${it.first}" }
            writer.println(
                """
    class $className($fields) : $baseName() {
        override fun <R> accept(visitor: Visitor<R>): R {
            return visitor.visit${className}${baseName}(this)
        }
    }
                """.trimIndent()
            )
        }
    }
}
